# prometheus/prometheus.yml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      # We use the container name 'cadvisor' because they share a docker network
      - targets: ['cadvisor:8080']